version: "2"


services:
    db:
        image: postgres:13
        expose:
            - ${DB_PORT}
        ports:
            - ${DB_PORT}:${DB_PORT}
        command: -p ${DB_PORT}
        environment:
            - POSTGRES_DB=${DB_DB}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USER}
        volumes:
            - db_data:/var/lib/postgresql/data

    backend:
        build: ./backend/src/
        depends_on:
            - db
        ports:
            - ${BACKEND_PORT}:${BACKENDB_PORT}
        env_file: .env


volumes:
    db_data:
        external: true